#############################################################################
# Makefile for building: praiseImport
# Generated by qmake (2.01a) (Qt 4.8.4) on: Sun May 26 00:25:51 2013
# Project:  praiseImport.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile praiseImport.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtWebKit -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = eaction.cpp \
		ebrowser.cpp \
		main.cpp \
		praisedownload.cpp \
		praiseimport.cpp moc_eaction.cpp \
		moc_ebrowser.cpp \
		moc_praisedownload.cpp
OBJECTS       = eaction.o \
		ebrowser.o \
		main.o \
		praisedownload.o \
		praiseimport.o \
		moc_eaction.o \
		moc_ebrowser.o \
		moc_praisedownload.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		praiseImport.pro
QMAKE_TARGET  = praiseImport
DESTDIR       = 
TARGET        = praiseImport

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_praiseimport.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: praiseImport.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtWebKit.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile praiseImport.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtWebKit.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile praiseImport.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/praiseImport1.0.0 || $(MKDIR) .tmp/praiseImport1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/praiseImport1.0.0/ && $(COPY_FILE) --parents eaction.h ebrowser.h praisedownload.h praiseimport.h .tmp/praiseImport1.0.0/ && $(COPY_FILE) --parents eaction.cpp ebrowser.cpp main.cpp praisedownload.cpp praiseimport.cpp .tmp/praiseImport1.0.0/ && $(COPY_FILE) --parents praiseimport.ui .tmp/praiseImport1.0.0/ && (cd `dirname .tmp/praiseImport1.0.0` && $(TAR) praiseImport1.0.0.tar praiseImport1.0.0 && $(COMPRESS) praiseImport1.0.0.tar) && $(MOVE) `dirname .tmp/praiseImport1.0.0`/praiseImport1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/praiseImport1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_eaction.cpp moc_ebrowser.cpp moc_praisedownload.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_eaction.cpp moc_ebrowser.cpp moc_praisedownload.cpp
moc_eaction.cpp: ebrowser.h \
		eaction.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) eaction.h -o moc_eaction.cpp

moc_ebrowser.cpp: ebrowser.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) ebrowser.h -o moc_ebrowser.cpp

moc_praisedownload.cpp: eaction.h \
		ebrowser.h \
		praisedownload.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) praisedownload.h -o moc_praisedownload.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_praiseimport.h
compiler_uic_clean:
	-$(DEL_FILE) ui_praiseimport.h
ui_praiseimport.h: praiseimport.ui
	/usr/lib/qt4/bin/uic praiseimport.ui -o ui_praiseimport.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

eaction.o: eaction.cpp eaction.h \
		ebrowser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eaction.o eaction.cpp

ebrowser.o: ebrowser.cpp ebrowser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ebrowser.o ebrowser.cpp

main.o: main.cpp ebrowser.h \
		praisedownload.h \
		eaction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

praisedownload.o: praisedownload.cpp praisedownload.h \
		eaction.h \
		ebrowser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o praisedownload.o praisedownload.cpp

praiseimport.o: praiseimport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o praiseimport.o praiseimport.cpp

moc_eaction.o: moc_eaction.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eaction.o moc_eaction.cpp

moc_ebrowser.o: moc_ebrowser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ebrowser.o moc_ebrowser.cpp

moc_praisedownload.o: moc_praisedownload.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_praisedownload.o moc_praisedownload.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

