######################################################################
# Automatically generated by qmake (2.01a) Sun May 26 00:25:24 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += eaction.h ebrowser.h praisedownload.h praiseimport.h
FORMS += praiseimport.ui
SOURCES += eaction.cpp ebrowser.cpp main.cpp praisedownload.cpp praiseimport.cpp
QT += network webkit
